---
# tasks file for sample-mysql
  - name: Create primary partition
    parted: 
      device: /dev/xvdf
      number: 1
      state: present
      part_end: "800MiB"
      fs_type: ext4
  - name: Add volume group
    lvg:
      vg: vg_database
      pvs: /dev/xvdf1
  - name: Create logical volume
    lvol:
      vg: vg_database
      lv: lv_mysql
      size: 512
  - name: Create the file system
    filesystem:
      fstype: xfs
      dev: /dev/mapper/vg_database-lv_mysql
  - name: Mount disk
    mount:
      src: /dev/mapper/vg_database-lv_mysql
      path: /mnt/mysql_backups
      state: mounted
      fstype: xfs
  - name: Install mysql
    yum:
      name: mysql-community-server
      state: present
...
    
